agent {
  trust_domain = "confluent.io"

  server_address = "spire-server"
  server_port    = "8081"

  data_dir  = "/opt/spire/data/agent"
  log_level = "INFO"

  # Bootstrap bundle written by `spire-server bundle show` (see steps below)
  trust_bundle_path = "/opt/spire/conf/agent/bootstrap.crt"

  workload_x509_svid_key_type = "rsa-2048"

  socket_path = "/var/run/spire-agent.sock"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "disk" {
    plugin_data {
      directory = "/opt/spire/data/agent"
    }
  }

  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
