security.protocol=SSL

ssl.keystore.type=PKCS12
ssl.keystore.location=./shared-secrets/kafka-keystore.p12
ssl.keystore.password=changeit
ssl.key.password=changeit

ssl.truststore.type=PKCS12
ssl.truststore.location=./shared-secrets/kafka-truststore.p12
ssl.truststore.password=changeit

ssl.endpoint.identification.algorithm=https
