server {
  bind_address = "0.0.0.0"
  bind_port    = "8081"

  trust_domain = "confluent.io"
  data_dir     = "/opt/spire/data/server"

  log_level = "INFO"

  default_x509_svid_ttl = "1h"

  ca_key_type = "rsa-2048"
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type     = "sqlite3"
      connection_string = "/opt/spire/data/server/datastore.sqlite3"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "memory" {
    plugin_data {}
  }
}
